version: '3'
services:
  speech-recognition:
    build:
      context: .
      args:
        config_path: config/$ENV
        base_image: python:3.8.16-slim-buster
    container_name: speech-recognition-container
    user: root
    image: dna/$SERVICE
    working_dir: /opt/dna/$SERVICE
    env_file:
      - config/$ENV/.env
    #  - .env
    ports:
      - ${JUPYTER_PORT-8085}:${JUPYTER_PORT-8085}
    volumes:
      - .:/opt/dna/$SERVICE
      - .:/src # Used by pre-commit on pytest step
      - ./config/$ENV:/home/jovyan/dna
      - ./datalake:/datalake
      - ./datalake/scikit_learn_data:/home/jovyan/scikit_learn_data
      - ./config/$ENV:/opt/speech/configs/cluster/
    entrypoint: ./config/$ENV/actions/run.sh
