lakes:
  transient: 'file:///datalake/$CUSTOMER_NAME/transient'
  raw: 'file:///datalake/$CUSTOMER_NAME/raw/$PARQUET_NAME.parquet'
  trusted: 'file:///datalake/$CUSTOMER_NAME/trusted/$PARQUET_NAME.parquet'
  refined: 'file:///datalake/$CUSTOMER_NAME/refined/$PARQUET_NAME.parquet'
  ml_experiment: 'file:///datalake/$CUSTOMER_NAME/ml_experiment/$PARQUET_NAME.parquet'
  models: 'file:///datalake/$CUSTOMER_NAME/models'
  backup: 'file:///datalake/$CUSTOMER_NAME/backup'
  secrets: 'file:///datalake/$CUSTOMER_NAME/secrets'
  config: 'file:///home/jovyan/dna'
  recipe: 'file:///datalake/recipe'
  save_csv: 'file:///datalake/$CUSTOMER_NAME/save/$PARQUET_NAME.csv'
  model: 'file:///datalake/$CUSTOMER_NAME/model'
  ml_engineer: 'file:///datalake/$CUSTOMER_NAME/ml_engineer/$PARQUET_NAME.parquet'
